# Generated by Django 4.2.13 on 2024-05-27 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=60)),
                ('cv', models.FileField(upload_to='cv')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('name_for_css', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('address', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='personal')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.cv')),
                ('social_media', models.ManyToManyField(to='about.socialmedia', verbose_name='Social Media')),
                ('technologies', models.ManyToManyField(to='about.technologies', verbose_name='Technologies')),
            ],
        ),
    ]
