# Generated by Django 4.2.13 on 2024-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('position_degree', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=8)),
                ('css_style', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='education',
            field=models.ManyToManyField(blank=True, to='about.education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='me',
            name='experience',
            field=models.ManyToManyField(blank=True, to='about.experience', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='me',
            name='statistics',
            field=models.ManyToManyField(to='about.statistic', verbose_name='Statistics'),
        ),
    ]
