# Generated by Django 4.2.13 on 2024-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_education_experience_statistic_me_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('small_description', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='projects')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='me',
            name='projects',
            field=models.ManyToManyField(blank=True, to='about.projects', verbose_name='Projects'),
        ),
    ]
